---
include:
  - board: seeeduino_xiao_ble
    shield: settings_reset

  - board: seeeduino_xiao_ble
    shield: corne_dongle prospector_adapter
    snippet: studio-rpc-usb-uart zmk-usb-logging
    cmake-args: DCONFIG_ZMK_STUDIO=y

  - board: nice_nano_v2
    shield: settings_reset

  - board: nice_nano_v2
    shield: corne_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  - board: nice_nano_v2
    shield: corne_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
