---
include:
  - board: seeeduino_xiao_ble
    shield: settings_reset

  - board: seeeduino_xiao_ble
    shield: corne_dongle
    snippet: studio-rpc-usb-uart zmk-usb-logging
    cmake-args: DCONFIG_ZMK_STUDIO=y

  - board: nice_nano_v2
    shield: settings_reset

  - board: nice_nano_v2
    shield: corne_left

  - board: nice_nano_v2
    shield: corne_right
