manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: legitcamper
      url-base: https://github.com/legitcamper
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-autocorrect-module
      remote: legitcamper
      revision: main
  self:
    path: config
